export const START_REGISTER_USER = "START_REGISTER_USER";
export const SUCCESS_REGISTER_USER = "SUCCESS_REGISTER_USER";
export const ERROR_REGISTER_USER = "ERROR_REGISTER_USER";

export const START_LOGIN_USER = "START_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
export const ERROR_LOGIN_USER = "ERROR_LOGIN_USER";

export const ADD_NEW_NOTIFICATION = "ADD_NEW_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";

export const START_GET_USER = "START_GET_USER";
export const SUCCESS_GET_USER = "SUCCESS_GET_USER";
export const ERROR_GET_USER = "ERROR_GET_USER";

export const START_GET_DASHBOARD = "START_GET_DASHBOARD";
export const SUCCESS_GET_DASHBOARD = "SUCCESS_GET_DASHBOARD";
export const ERROR_GET_DASHBOARD = "ERROR_GET_DASHBOARD";
