export const START_GET_LEAVES = "START_GET_LEAVES";
export const SUCCESS_GET_LEAVES = "SUCCESS_GET_LEAVES";
export const ERROR_GET_LEAVES = "ERROR_GET_LEAVES";

export const START_ADD_LEAVE = "START_ADD_LEAVE";
export const SUCCESS_ADD_LEAVE = "SUCCESS_ADD_LEAVE";
export const ERROR_ADD_LEAVE = "ERROR_ADD_LEAVE";

export const START_LEAVE_ACTON = "START_LEAVE_ACTON";
export const SUCCESS_LEAVE_ACTON = "SUCCESS_LEAVE_ACTON";
export const ERROR_LEAVE_ACTON = "ERROR_LEAVE_ACTON";

export const START_DELETE_LEAVE = "START_DELETE_LEAVE";
export const SUCCESS_DELETE_LEAVE = "SUCCESS_DELETE_LEAVE";
export const ERROR_DELETE_LEAVE = "ERROR_DELETE_LEAVE";

export const START_EDIT_LEAVE = "START_EDIT_LEAVE";
export const SUCCESS_EDIT_LEAVE = "SUCCESS_EDIT_LEAVE";
export const ERROR_EDIT_LEAVE = "ERROR_EDIT_LEAVE";
